site_name: PCL Tutorials

# Documentation and theme
theme:
  name: "readthedocs"
  language: "en"
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"

extra_css:
  - "stylesheets/code-tabs.css"

extra_javascript:
  - "javascripts/main.js"
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: True
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: "active"
      template: "default"
  - pymdownx.arithmatex:
      generic: true

# Copyright
copyright: 'arjunskumar22@gmail.com'
site_name: PCL Tutorials
site_description: My Notes on PCL 
site_author: Arjun S Kumar
site_url: https://arjunskumar.github.io/pcl_tutorials/

# Repository
repo_name: arjunskumar/pcl_tutorials
repo_url: https://github.com/arjunskumar/pcl_tutorials
edit_uri: ""


# Page tree
nav:
  - Install PCL: index.md
  - Reading PCD: read_pcd.md 
  - Writing PCD: write_pcd.md



# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
